---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  labels:
    run: orderms-svc
  name: orderms-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: orderms-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: orderms-svc
    spec:
      containers:
      - name: orderms-svc
        image: docker.io/gzapataz/orderms
        imagePullPolicy: IfNotPresent
        env:
          - name: API_QUEUE
            value: "ec2-18-221-227-247.us-east-2.compute.amazonaws.com"
        ports:
        - containerPort: 3010
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: orderms-svc
  name: orderms-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000 
  selector:
    run: orderms-svc
  sessionAffinity: None
  type: LoadBalancer
